// react-app/src/App.js
import "./App.css";
import { useEffect, useRef, useState } from "react";

function App() {
  // State variables
  const [todos, setTodos] = useState([]);

  // Binding variables
  const todoText = useRef();

  // Lifecycle Hooks
  useEffect(() => {
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem("todos", JSON.stringify(next));
  }
  return (
    <>
      <div className="container">
        <form onSubmit={addTodo}>
          <input
            type="text"
            ref={todoText}
            placeholder="what needs to be done?"
            className="textInput"
          
          />
          <input type="submit" value="Add ToDo" className="button" />
        </form>
      </div>
      <div className="list">
        <ul id="todos">
          {todos.map((todo) => (
            <li key={todo}>{todo}</li>
          ))}
        </ul>
      </div>
    </>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ToDo } from './todo-model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'angular-app';
  textInput!: string;
  todoList: string[] = [];
  existingTodos: string[] = [];

  ngOnInit() {
    this.existingTodos = JSON.parse(localStorage.getItem("todos")!)
  }

  onSubmit(): void {
    console.log(this.textInput);
    // push vs concat
    this.todoList = this.todoList.concat(this.textInput)
    localStorage.setItem("todos", JSON.stringify(this.todoList));
  }
}
<h1>Angular ToDo</h1>
<div class="container">
  <form>
    <input
      name="todo"
      type="text"
      class="textInput"
      placeholder="what needs to be done?"
      [(ngModel)]="textInput"
    />
    <input type="submit" value="Add Todo" class="button" (click)="onSubmit()" />
  </form>
</div>
<div class="list">
  <ul id="todos">
    <li *ngFor="let item of existingTodos">{{ item }}</li>
    <li *ngFor="let item of todoList">{{ item }}</li>
  </ul>
</div>
